* There is a problem with the plugin creator functions when declaring them    extern C LIMBX_API. They returned an MRef to a plugin. Example error:      error C2526: 'mg711_LTX_getPlugin' : C linkage function cannot return C++ class MRef<OPType>
   I changed from "MRef<MObject*>" to "MObject*". If you don't
   like this, please shout.

 * Note that in AudioPlugin.cxx, I have changed from:
         MRef<MPlugin *> *maudio_LTX_getPlugin( MRef<Library*> lib )
   to
         MPlugin * maudio_LTX_getPlugin( MRef<Library*> lib )
     
   Note the extra "*" before the function name that other "getPlugin" 
   functions don't have. I don't see how it can be needed.

 * Fixed a wrong ifdef (to discard MSVC * pragmas)